# Generated by Django 3.2.5 on 2021-07-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='video_blob_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
